name: Build TinyALSA for Android ARM64 and ARM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'TinyALSA commit hash or tag to build'
        required: false
        default: 'master'

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TinyALSA source
        uses: actions/checkout@v4
        with:
          repository: tinyalsa/tinyalsa
          ref: ${{ github.event.inputs.version }}

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "$PWD/android-ndk-r25c" >> $GITHUB_PATH

      - name: Build TinyALSA for ARM64
        run: |
          export NDK_TOOLCHAIN_PREFIX=$PWD/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64
          export PATH=$NDK_TOOLCHAIN_PREFIX/bin:$PATH
          make -j$(nproc)
          
      - name: Archive ARM64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinyalsa-arm64-binaries
          path: |
            utils/tinycap
            utils/tinymix
            utils/tinyplay
  
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TinyALSA source
        uses: actions/checkout@v4
        with:
          repository: tinyalsa/tinyalsa
          ref: ${{ github.event.inputs.version }}

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "$PWD/android-ndk-r25c" >> $GITHUB_PATH

      - name: Build TinyALSA for ARM (32-bit)
        run: |
          export NDK_TOOLCHAIN_PREFIX=$PWD/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64
          export PATH=$NDK_TOOLCHAIN_PREFIX/bin:$PATH
          make -j$(nproc) TARGET_ARCH=arm
          
      - name: Archive ARM (32-bit) artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinyalsa-arm-binaries
          path: |
            utils/tinycap
            utils/tinymix
            utils/tinyplay
