name: Build TinyALSA for Android ARM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'TinyALSA commit hash or tag to build'
        required: false
        default: 'master'

jobs:
  build_arm:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout TinyALSA source
        uses: actions/checkout@v4
        with:
          repository: tinyalsa/tinyalsa
          ref: ${{ github.event.inputs.version }}

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "$PWD/android-ndk-r25c" >> $GITHUB_PATH

      - name: Create Android.mk
        run: |
          cat > Android.mk <<EOF
          LOCAL_PATH := $(call my-dir)

          include $(CLEAR_VARS)
          LOCAL_MODULE := tinyalsa_library
          LOCAL_SRC_FILES := src/mixer.c src/pcm.c src/pcm_plugin.c src/limits.c
          LOCAL_C_INCLUDES := include
          include $(BUILD_STATIC_LIBRARY)

          include $(CLEAR_VARS)
          LOCAL_MODULE := tinycap
          LOCAL_SRC_FILES := utils/tinycap.c
          LOCAL_STATIC_LIBRARIES := tinyalsa_library
          LOCAL_C_INCLUDES := include
          include $(BUILD_EXECUTABLE)

          include $(CLEAR_VARS)
          LOCAL_MODULE := tinyplay
          LOCAL_SRC_FILES := utils/tinyplay.c
          LOCAL_STATIC_LIBRARIES := tinyalsa_library
          LOCAL_C_INCLUDES := include
          include $(BUILD_EXECUTABLE)

          include $(CLEAR_VARS)
          LOCAL_MODULE := tinymix
          LOCAL_SRC_FILES := utils/tinymix.c
          LOCAL_STATIC_LIBRARIES := tinyalsa_library
          LOCAL_C_INCLUDES := include
          include $(BUILD_EXECUTABLE)
          EOF

      - name: Create Application.mk for 32-bit
        run: |
          cat > Application.mk <<EOF
          APP_ABI := armeabi-v7a
          APP_STL := c++_static
          APP_PLATFORM := android-21
          EOF
      
      - name: Build TinyALSA for ARM (32-bit) with ndk-build
        run: |
          export NDK_ROOT=$PWD/android-ndk-r25c
          $NDK_ROOT/ndk-build -j$(nproc)

      - name: Archive ARM (32-bit) artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tinyalsa-arm-binaries
          path: |
            libs/armeabi-v7a/tinycap
            libs/armeabi-v7a/tinymix
            libs/armeabi-v7a/tinyplay
